### ISSUE TITLE
Error building with Dockerfile

### ISSUE THREAD

**Issue by ghost** [amplab/ampcrowd#14]
I get the following errors when trying to build from the Dockerfile - after download from GIT.

Can you provide any assistance on how I can resolve?

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 871, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 595, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 563, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 552, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 353, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 310, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 2
ubuntu@ip-XXX-YY-ZZ-AA://home/ubuntu/ampcrowd/ampcrowd$ docker build -f /home/ubuntu/ampcrowd/ampcrowd/Dockerfile

**Comment by thisisdhaas** [comment]
Looks like this is an out of memory error coming when pip tries to install the requirements file. Does your docker machine have a reasonable amount of memory? You could also try modifying the `requirements.txt` file to see if a specific package is causing the error.

**Comment by ghost** [comment]
Thanks, I did spin up a new AWS EC2 instance with more memory and my build seemed to work.  I will post another question separately about an issue with run.
